### ISSUE TITLE
HTTP responses are cached

### ISSUE THREAD

**Issue by dmalopsy** [sergeylukin/mql4-http#1]
HTTP responses are cached with the same value and are not cleared until MT4 is restarted. I suspect INTERNET_FLAG_RELOAD or similar may need to be set.

**Comment by mike59999** [comment]
Hi,

i had the same problem with caching. I have appended to the url a random snippet.
At the end of the url you can place &random=" + TimeCurrent() + "".
The URL is now unique and called everytime you need it.
